{% set version = "1.3.0" %}

package:
  name: shellingham
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/shellingham/shellingham-{{ version }}.tar.gz
  sha256: a1bc8cbe437e5348c242d4e8145242d364d9493034ed790a82991c0e2d3ad984

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - shellingham
    - shellingham.posix

about:
  home: https://pypi.org/project/shellingham
  license: ISC (ISCL)
  license_file: LICENSE
  summary: Tool to Detect Surrounding Shell

extra:
  recipe-maintainers:
    - ocefpaf
