travis:
  secure:
    BINSTAR_TOKEN: bVZzfKGwMjQNp2Mwk34DajVVPHPclY4no6nFlRivJnUiu2a8tBIVQBN3HY/5Cv9svvKDRt0CzHsxP+mQXMfnAsdL1a1JveIpOl0S8vVyFQNQlrBQLZG9z2cU9s5eGro0iS1LgWULFUMcKc2eDAtQBizTp74j74qHEnDfy496fENFcE5KLjbFeLFU4QcrVVoPXwQxbGahrleSkLnKIPtw442EDvaiW7UFmBwcFt6GKOU+tyCbjCxNv9TidA1CzsS3hyJwWGjuppBDdWU35eXK/gQOipuNF9FxbqaHhlDoS568z5c6rWzeI7QKAeTpdFjZcRroHvgNOKWvalOrFQ/lYpX9Z+hn20hec+/FkYONJXkvqBXBbTb2pTGSZG5qWZfhAccjWBYN65DhEp/eB1zUseovsjv4guQE0c7R7J5V/ItQgAyp0tWElJNLzjrmZJxRqGLWgT8XuRF8MMBslypIDPV2MR1Y7VnPiuZcxOgazHHUPd+FLVRSg/CZUC9jLWSn8fQS7g1EwnFMsY3tBetWL2DOQibx6+9qbkyg9rW/8bYzsoSaTQ2OCwBXU7m8xaTSHi8ZcZllbIhwVt/yzCzIfkX5EAkvHeCtqSX9D+GYRMb0TfT3cmc9qt6dew1rQ1xICyZ4nGwmOcaEMbKo92HdrwNhih3XsZ3AaLcX4ZaBjYA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
